version: '3.8'
services:

  payment-service:
    build: ./plutus-payment
    ports:
      - "8080:8080"

  user-service:
    build: ./plutus-user
    ports:
      - "8081:8081"

  wallet-service:
    build: ./plutus-wallet
    ports:
      - "8082:8082"

  payment-provider-service:
    build: ./payment-provider
    ports:
      - "8083:8083"

  psql-db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - plutus-db:/var/lib/postgresql
    environment:
      POSTGRES_USER: plutus
      POSTGRES_PASSWORD: plutus
      POSTGRES_DB: plutus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana grafana/grafana
    depends_on:
      - prometheus

volumes:
  plutus-db:
  grafana-storage:
